name: "towndex gui"
description: "Generate a towndex static site from input document metadata"
author: "Minor Gordon"
branding:
  icon: "loader"
inputs:
  configuration:
    description: Path to a configuration.json file, which controls the static site generator.
    required: false
  debug:
    description: Debug the action
    required: false
  input:
    description: Path to a directory of a document metadata (.json/.yaml).
    required: true
  output:
    description: Path to a directory to write the generated static site.
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
