name: "towndex gui"
description: "Generate a towndex static site from input document metadata"
author: "Minor Gordon"
branding:
  icon: "loader"
inputs:
  cache:
    description: Path to a directory to use for caching
    required: false
  configuration:
    description: Path to a configuration.json file, which controls the static site generator
    required: false
  debug:
    description: Debug the action
    required: false
  input:
    description: Path to a directory of document metadata files (.json/.yaml)
    required: true
  output:
    description: Path to a directory to write the generated static site
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
